import type { Metadata } from "next";
import { Atma, Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/Navbar";
import { Container } from "@/components/Container";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Container>
          <Navbar />
        </Container>
        {children}
      </body>
    </html>
  );
}
